# .gitlab-ci.yml
stages:
  - test

test_job:
  stage: test
  image: eclipse-temurin:17-jdk-jammy
  script:
    - ./gradlew testDebugUnitTest jacocoTestReport
  artifacts:
    when: always
    reports:
      junit: app/build/test-results/testDebugUnitTest/*.xml
      coverage_report:
        coverage_format: cobertura
        path: app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
  only:
    - merge_requests
    - main